name: maingame
version: '1.0-SNAPSHOT'
main: org.naingame.maingame.Maingame
api-version: '1.21'
authors: [ pazdan5lllkkkk ]
description: maianigame

commands:
  minegame:
    description: huuuh
    permission: MG.meingu

permissions:
  MG.meingu:
    description: Open Main Menu
    default: not op
